SELECT DISTINCT NOMR, NOMC FROM (((formation2.VENTES
INNER JOIN formation2.CLIENTS ON VENTES.NC = CLIENTS.NC)
INNER JOIN formation2.PRODUITS ON VENTES.NP = PRODUITS.NP)
INNER JOIN formation2.REPRESENTANTS ON VENTES.NR = REPRESENTANTS.NR)
WHERE COUL='Rouge' AND QT>100;